// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suisrrsmangoaadjoovj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1aXNycnNtYW5nb2FhZGpvb3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MDI4NTcsImV4cCI6MjA2MjA3ODg1N30.b-fk__OTYn2Eim9rqtetpacEst41xhxtxeTY2wE0gLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // CRITICAL: Ensure session persistence in iOS WebView
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    storageKey: 'sb-suisrrsmangoaadjoovj-auth-token',
  },
});